# installiung all the required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
  exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.10.100"
    config.hostsupdater.aliases = ["web.local"]
    config.vm.synced_folder "node-sample-app", "/app"
    config.vm.provision :shell, path: "nginx.sh", privileged:false
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.10.101"
    #config.hostsupdater.aliases = ["db.local"]
    config.vm.synced_folder "node-sample-app", "/app"
    config.vm.provision :shell, path: "mongo.sh", privileged:false
  end

end
